### ISSUE TITLE
Array to string conversion notice for "query" components.

### ISSUE THREAD

**Issue by mcaskill** [ivantcholakov/http_build_url#1]
Hello,

I was comparing implementations of `http_build_url()` against a few others using your own tests and the PHPUnit tests made by @jakeasmith' for his `[http_build_url](/jakeasmith/http_build_url)` implementation.

His implementation failed a few of your tests and your implementation fails two tests of his:
- `testUrlQueryArrayIsIgnored`
- `testPartsQueryArrayIsIgnored`

I can't decipher the original C code to see if these assertions are taken into account but I thought I'd highlight this with you.

I've added these two conditions in your implementation to pass the PHPUnit test:

``` php
if (isset($url['query']) && !is_string($url['query'])) {
    $url['query'] = null;
}

if (isset($parts['query']) && !is_string($parts['query'])) {
    $parts['query'] = null;
}
```

What are your toughts?

**Comment by ivantcholakov** [comment]
What I did is to make an exact porting of the C code. What @jakeasmith does is an interpretation of the behavior of the function, but it does not look to be close enough to the C code. I can not say whether his tests are correct and I don't care, frankly.

When I developed this code, I run my tests against the installed PECL function, then I uninstalled it. And then I run the same tests against the PHP-implemented function. Results were the same.

My approach is not test-driven. I simply "decipher" the C code.

**Comment by ivantcholakov** [comment]
@mcaskill The title: "Array to string conversion notice for "query" components."

Did you really see this notice with my PHP implementation? Can you give me a simple example (without PHPUnit code) how to reproduce this notice if it exists?

**Comment by ivantcholakov** [comment]
``` php
    public function testPartsQueryArrayIsIgnored()
    {
        $expected = $this->full_url; // "http://user:pass@www.example.com:8080/pub/index.php?a=b#files"
        $actual   = http_build_url($this->full_url, array('query' => array('foo' => 'bar')));
        $this->assertSame($expected, $actual);
    }
```

testPartsQueryArrayIsIgnored() - I am not sure that this test is correct, because HTTP_URL_REPLACE is default, see http://php.net/manual/en/function.http-build-url.php

**Comment by ivantcholakov** [comment]
``` php
    public function testUrlQueryArrayIsIgnored()
    {
        $expected = 'http://user:pass@www.example.com:8080/pub/index.php#files';
        $url      = parse_url($this->full_url); // "http://user:pass@www.example.com:8080/pub/index.php?a=b#files"
        parse_str($url['query'], $url['query']);
        $actual = http_build_url($url);
        $this->assertSame($expected, $actual);
    }
```

I am not sure for this one, but at least it shows array to string conversion.

**Comment by ivantcholakov** [comment]
https://github.com/jakeasmith/http_build_url/issues/2

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/http_build_url/commit/290b3cf9dc50bf78e91aba14884c20ff1f7354a0

**Comment by ivantcholakov** [comment]
@mcaskill Version 1.7.6.2 has been released, thank you very much.

**Comment by ivantcholakov** [comment]
Version 1.7.6.3 - minor corrections.

**Comment by mcaskill** [comment]
Oh, wow. You went on ahead with this. Cool. I agree that it is unfortunate the original function ignores 'query' parts of array types. It should have been able to accept arrays and just implode them with `http_build_query`.

Thanks for the quick tackle of this. Great implementation, by the way!
